### ISSUE TITLE
非Docker时的运行参数缺少`get_ip_api`

### ISSUE THREAD

**Issue by quan787** [iskoldt-X/SRUN-authenticator#4]
在readme中加入就好了：

> 非Docker 运行校园网深澜认证Python 脚本
编辑如下三个变量，分别是接入校园网的网口名字，用户名和密码。
> ```
> interfacelist = ['']
> username=''
> password=''
> ```
> 用户还要更改：
> ```
> ➕get_ip_api='http://124.16.81.61/cgi-bin/rad_user_info?callback=JQuery'
> init_url="https://portal.ucas.ac.cn"
> get_challenge_api="https://portal.ucas.ac.cn/cgi-bin/get_challenge"
> srun_portal_api="https://portal.ucas.ac.cn/cgi-bin/srun_portal"
> ```

**Comment by iskoldt-X** [comment]
这就加上😄
